---
- name: "PLAY1: Manage NTP Configuration"
  hosts: "all"
  tasks:
    - name: "TASK0: Validate NTP Servers"
      assert:
        that:
          - "ntp_server1 is defined"
          - "ntp_server2 is defined"
          - "ntp_server1 | ipv4 == ntp_server1"
          - "ntp_server2 | ipv4 == ntp_server2"

    - name: "TASK1: Apply NTP updates"
      ios_config:
        lines:
          - "ntp authenticate"
          - "ntp logging"
          - "ntp server {{ ntp_server1 }}"
          - "ntp server {{ ntp_server2 }}"
      register: "ntp_changes"

    - name: "TASK2: Print changes if NTP config changed" 
      debug:
        var: "ntp_changes.updates"
      when: "ntp_changes.updates is defined"
